### ISSUE TITLE
NPM dependency warning message

### ISSUE THREAD

**Issue by aculligan** [uncss/postcss-uncss#12]
When installing postcss-uncss, npm installs the latest version of uncss [0.17.0](https://www.npmjs.com/package/uncss). There's a warning message asking for 0.16.1. 

`npm WARN postcss-uncss@0.16.1 requires a peer of uncss@^0.16.1 but none is installed. You must install peer dependencies yourself.`

One could manually install 0.16.1, but this pluging works well with 0.17.0, so there's no need for that.

Easy fix is to update the [package.json](https://github.com/uncss/postcss-uncss/blob/master/package.json) file to requeste version 0.17.0 of uncss.

I'll submit a PR.

**Comment by RyanZim** [comment]
Fixed in #13.
