### ISSUE TITLE
Postcss v7.0.2 compatibility

### ISSUE THREAD

**Issue by edsonv** [uncss/postcss-uncss#5]
How can I make it to work on the version of postcss described in the title?

**Comment by RyanZim** [comment]
It should be perfectly compatible, are you experiencing an issue?

**Comment by edsonv** [comment]
Thanks for the reply. I didn't explained myself, sorry... I was trying to use it on webpack with the postcss version pointed but an error jumps stating that the plugin is complatible with version 6 of postcss.

**Comment by RyanZim** [comment]
Where's that error coming from? It's true that they use different versions, but there's no actual compatibility issues.

**Comment by edsonv** [comment]
Now I understand. But despite that the bundle with webpack does not occur. I will double check again and add comments. Thanks Ryan

**Comment by ednjv** [comment]
I'm getting this error

```
Unknown error from PostCSS plugin. Your current PostCSS version is 7.0.6, but uncss uses 6.0.23. Perhaps this is the source of the error below.
```

**Comment by RyanZim** [comment]
@ednjv What's the error below?

**Comment by ednjv** [comment]
@RyanZim 
```
Error: UnCSS: no HTML files found
```

Maybe it's something on my side, I have the following on my `postcss.config.js`
```
module.exports = {
  plugins: {
    'postcss-import': {},
    'postcss-url': {},
    'precss': {},
    'autoprefixer': {},
    'postcss-uncss': {},
    'cssnano': {}
  }
};
```

**Comment by RyanZim** [comment]
Yeah, you need to pass the `html` option to `postcss-uncss`, with your HTML files.

**Comment by ednjv** [comment]
@RyanZim dear god, I'm dumb, thanks for the quick reply
